### PR TITLE
Program now only de/encrypts files in a certain directory

### PR DESCRIPTION
**Pull request by Feuerwerko**
I also removed a variable that was declared in the encryptor and decryptor but never used.

### CODE REVIEW

**Comment by WilliamAfton-codes** [comment]
Although your modified script creates a new folder, named VAULT, there appears to be no reference to the folder anywhere in the rest of the code.

Comments: After running your `encryptor.py`, there are a few errors:
1) Your syntax is incorrect. You must use `os.chdir("VAULT")` instead of `os.chdir("./VAULT")
2) There is also no code in the script to create a directory called 'VAULT', therefore if you run the program it will encounter an error

Did you run and test the program before submitting a pull request? Since the program does not run correctly, I will reject this pull request

**Comment by WilliamAfton-codes** [comment]
Another comment before I close the request, this code on line 30-31 does have a purpose

```
if file[-3:] == ".py":
        continue
```

this code makes sure that the program does not encrypt itself. If alterations are made, I would be happy to accept the pull request

**Comment by WilliamAfton-codes** [comment]
One more thing, I liked your idea for the program so I will implement it myself, and I will credit you in the code :)

**Comment by Feuerwerko** [comment]
> Another comment before I close the request, this code on line 30-31 does have a purpose
> 
> ```
> if file[-3:] == ".py":
>         continue
> ```
> 
> this code makes sure that the program does not encrypt itself. If alterations are made, I would be happy to accept the pull request

I was talking about a diffrent line. The line asigned the current working directory to a variable but was never used.

**Comment by Feuerwerko** [comment]
> Although your modified script attempts to go to a new folder, named VAULT, there appears to be no creation of the folder anywhere in the rest of the code.
> 
> Comments: After running your `encryptor.py`, there are a few errors:
> 
> 1. Your syntax is incorrect. You must use `os.chdir("VAULT")` instead of `os.chdir("./VAULT")
> 2. There is also no code in the script to create a directory called 'VAULT', therefore if you run the program it will encounter an error
> 
> Did you run and test the program before submitting a pull request? Since the program does not run correctly, I will reject this pull request

I did test the program. The VAULT folder already exists by standard so there is no need for creating it.

**Comment by WilliamAfton-codes** [comment]
After re-checking your program; while it _does_ work when there is the 'VAULT' folder, it is preferable to include the folder within the code. Just to be explicit, when copying your code there is **_not_** a VAULT folder included in the source code.

About the unused code, you were right; it was development code left in by mistake. It does not affect the program regardless, but I'm glad you caught that. Either make the changes and submit a new pull request, or I will gladly make the changes and credit your work.

**Comment by WilliamAfton-codes** [comment]
Please leave your response within a week or I will do the latter of two options.

**Comment by WilliamAfton-codes** [comment]
@Feuerwerko instead of communicating here, here is my public Email address: williamafton.codes@gmail.com

Please talk to me directly from Email

**Pull request closed without merging**
